spring:
  mail:
    host: smtp.sina.com
    username: lishiru0611@sina.com
    password: 5969a9df39eeb07a
  rabbitmq:
    addresses: 139.9.142.46
    username: admin
    password: admin
    virtual-host: /test
    port: 5672
  security:
    jwt:
      key: abcdefghijk
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reborn_project
    username: root
    password: 123